### ISSUE TITLE
Kruinhoogte

### ISSUE THREAD

**Issue by jayesnl** [breinbaas/uitgangspuntenapp#5]
Is het niet handig om de kruinhoogte van AHN3 over te nemen dan de kruinhoogte van andere layers. 
AHN3 is leidend als er geen metingen beschikbaar zijn.

**Comment by breinbaas** [comment]
Misschien is kruinhoogte misleidend, ik bedoel dijktafelhoogte dus ik maak er een issue van om kruinhoogte om te zetten naar minimale dijktafelhoogte

**Comment by breinbaas** [comment]
Omgezet naar dijktafelhoogte
